spring:
  profiles:
    active:
    - dev
---
spring:
  application:
    name: lopez-springcloud-eureka
  profiles: dev
server:
  port: 9001
eureka:
  instance:
        # 服务续约任务调用的间隔时间    lease-renewal-interval-in-seconds: 30
        # 服务时效的时间
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  application:
    name: lopez-springcloud-eureka
  profiles: prod
server:
  port: 9002
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90    
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: false
    fetch-registry: false      
---
spring:
  application:
    name: lopez-springcloud-eureka
  profiles: test
server:
  port: 9003
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90    
  client:
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
    register-with-eureka: false
    fetch-registry: false